name: Toposes
version: "2020.07.03"
license: "GPL-2.0-or-later"
date: 2020-07-03
description: |
    Elementary toposes

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/
    - name: Mario Román
      url: https://mroman42.github.io/
    - name: Tom Kuhmichel
      url: https://github.com/TKuh

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/
    - name: Mario Román
      url: https://mroman42.github.io/
    - name: Tom Kuhmichel
      url: https://github.com/TKuh

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2020.05.16"
      url: "https://homalg-project.github.io/CAP_project/CAP"

suggested-pkgs:
    - name: "MonoidalCategories"
      version: ">= 2019.03.16"
      url: "https://homalg-project.github.io/CAP_project/MonoidalCategories"

www: https://homalg-project.github.io/Toposes
readme: README.md
packageinfo: https://homalg-project.github.io/Toposes/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/Toposes/releases/download/v2020.07.03/Toposes-2020.07.03.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    elementary toposes.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BZRK20</span>]   <b class='BibAuthor'>Barakat, M., Zickgraf, F., Román, M. and Kuhmichel, T.</b>,
     <i class='BibTitle'>Toposes, Elementary toposes,
             Version 2020.07.03</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/Toposes">https://homalg-project.github.io/Toposes</a></span>.
    </p>
    

bibtex: |
    @misc{ Toposes2020.07.03,
      author =           {Barakat, M. and Zickgraf, F. and Rom{\a'a}n, M. and Kuhmichel, T.},
      title =            {{Toposes}, Elementary toposes, {V}ersion 2020.07.03},
      month =            {Jul},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://homalg-project.github.io/Toposes} {\texttt{https://homalg-project.github.io/}\discretionary {}{}{}\texttt{Toposes}}},
      keywords =         {elementary toposes},
      printedkey =       {BZRK20}
    }

