name: Toposes
version: "2022.08-01"
license: "GPL-2.0-or-later"
date: 2022-08-08
description: |
    Elementary toposes

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/
    - name: Mario Román
      url: https://mroman42.github.io/
    - name: Tom Kuhmichel
      url: https://github.com/TKuh

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/
    - name: Mario Román
      url: https://mroman42.github.io/
    - name: Tom Kuhmichel
      url: https://github.com/TKuh

GAP: ">= 4.11.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2022.03-06"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "CartesianCategories"
      version: ">= 2022.08-01"
      url: "https://homalg-project.github.io/pkg/CartesianCategories"

suggested-pkgs:
    - name: "CategoryConstructor"
      version: ">= 2022.06-02"
      url: "https://homalg-project.github.io/pkg/CategoryConstructor"
    - name: "MonoidalCategories"
      version: ">= 2022.05-03"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "Digraphs"
      version: ">= 1.3.1"
      url: "https://digraphs.github.io/Digraphs"

www: https://homalg-project.github.io/pkg/Toposes
readme: README.md
packageinfo: https://homalg-project.github.io/Toposes/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/Toposes/releases/download/v2022.08-01/Toposes-2022.08-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/Toposes/releases/download/v2022.08-01/Toposes-2022.08-01.zip

pdf: https://github.com/homalg-project/Toposes/releases/download/v2022.08-01/Toposes-2022.08-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    elementary toposes.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BZRK22</span>]   <b class='BibAuthor'>Barakat, M., Zickgraf, F., Román, M. and Kuhmichel, T.</b>,
     <i class='BibTitle'>Toposes, Elementary toposes,
             Version 2022.08-01</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/Toposes">https://homalg-project.github.io/pkg/Toposes</a></span>.
    </p>
    

bibtex: |
    @misc{ Toposes2022.08-01,
      author =           {Barakat,  M.  and  Zickgraf, F. and Rom{\a'a}n, M. and
                          Kuhmichel, T.},
      title =            {{Toposes}, Elementary toposes, {V}ersion 2022.08-01},
      month =            {Aug},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href   {https://homalg-project.github.io/pkg/Toposes}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{Toposes}}},
      keywords =         {elementary toposes},
      printedkey =       {BZRK22}
    }

